// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/aside/AsideMenu.vue')['default']
    AsideMenuMiniScreen: typeof import('./src/components/aside/AsideMenuMiniScreen.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterView: typeof import('./src/components/footer/FooterView.vue')['default']
    LoadingView: typeof import('./src/components/loading/LoadingView.vue')['default']
    NavBar: typeof import('./src/components/navbar/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchView: typeof import('./src/components/search/searchView.vue')['default']
  }
}
